### PR TITLE
Feature extentions

### PR DESCRIPTION
**Pull request by jwillmer**
## What I did
- Structured the css with less
- Modified quote style
- Added style for `figure` to allow images with caption
- Updated the docu with screenshots of my changes

### CODE REVIEW

**Comment by serenader2014** [comment]
Hi, thank you for your contributions, your improvements are perfect!

I have planned to rewrite the style, and add some features to the theme, and this weekend I finally have time to do this. 

After two day's work, I completely rewrite the style, use Sass to organize the style, and use Gulp to build script.

I follow your improvements such as quote with author, and image with caption, that was great! And I do a lot in image caption and gallery. You can check it out in the repo. I have updated the documentation.

**Comment by jwillmer** [comment]
I see it, cool that took my features. Are you planing to implement the "UP BUTTON" as well?

**Comment by serenader2014** [comment]
I can't find any doc about "UP BUTTON", is it a Ghost blog feature? If so, probably I will.

**Comment by jwillmer** [comment]
Button shows up if there is space (device width > X) and the user scrolled at least 400px down. Click on the button scrolls back to the top of the document.
image

Search for `.scrollup` in the css.

**Comment by serenader2014** [comment]
Feature added. Checkout the latest release. :)

**Comment by jwillmer** [comment]
Do you intend to implement the styling of quotes as well? I started to [translate the theme](https://github.com/jwillmer/jekyllDecent/blob/master/README.md) for a html generator. I like to have slightly more color in the theme and I ask because if you don't like it I need to modify it on the translated theme instead of merging.

**Pull request closed without merging**
